### ISSUE TITLE
Add Menu creation

### ISSUE THREAD

**Issue by BearlessDev** [BearlessDev/LobbyManager#1]
It will be cool if we can create custom menu via the config file like this:

```Yaml
Menu:
  main-menu:
    size: 54
    display_name: "&cMain Menu"
```

or something like that !
